version: '3.1'

services:
  db:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-db:1.0.0
    build:
      context: mysql/
      dockerfile: Dockerfile
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    restart: always
    environment:
      MYSQL_DATABASE: seat-records
      MYSQL_USER: whu-lib
      MYSQL_PASSWORD: Ab12345678..c
      MYSQL_ROOT_PASSWORD: ${SEAT_DB_ROOT_PASSWD}
    volumes:
      - seat-db:/var/lib/mysql/
      - ./mysql/init_scripts/:/docker-entrypoint-initdb.d/
    networks:
      - network
  recorder:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-records:1.1.0
    build:
      context: recorder/
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
    restart: always
    # ports:
    #   - 3001:3001
    depends_on:
      - db
    networks:
      - network
  ghauth:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-ghauth:1.1.0
    build:
      context: ghauth/
      dockerfile: Dockerfile
    environment:
      WHU_SEAT_CLIENT_SCERET: ${SEAT_GHAUTH_CLIENT_SCERET}
    restart: always
    # ports:
    #   - 3002:3002
    networks:
      - network
  nginx:
    image: docker.pkg.github.com/cs-tao/whu-library-seat-docker/seat-nginx:1.0.0
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
      - ./nginx/seat.conf:/etc/nginx/conf.d/seat.conf:ro
      - ./nginx/assets/:/home/seat/assets/
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - recorder
      - ghauth
    networks:
      - network

volumes:
  seat-db:

networks:
  network:
