name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install docker-compose
      env:
        DOCKER_COMPOSE_VERSION: 1.24.1
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin
    - name: Build images for github registry
      env:
        SEAT_ADMIN_NAME: ${{ secrets.SEAT_ADMIN_NAME }}
        SEAT_DB_ROOT_PASSWD: ${{ secrets.SEAT_DB_ROOT_PASSWD }}
        SEAT_RECORDER_PORT: ${{ secrets.SEAT_RECORDER_PORT }}
        SEAT_GHAUTH_PORT: ${{ secrets.SEAT_GHAUTH_PORT }}
        SEAT_GHAUTH_CLIENT_SCERET: ${{ secrets.SEAT_GHAUTH_CLIENT_SCERET }}
      run: docker-compose build
    - name: Deploy images to github registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEAT_GHAUTH_PORT: ${{ secrets.SEAT_GHAUTH_PORT }}
        SEAT_GHAUTH_CLIENT_SCERET: ${{ secrets.SEAT_GHAUTH_CLIENT_SCERET }}
      if: github.ref == 'refs/heads/master'
      run: |
        docker login docker.pkg.github.com -u CS-Tao -p "$GITHUB_TOKEN"
        docker-compose push

    - name: Swich to docker hub image builder
      if: github.ref == 'refs/heads/master'
      run: |
        sed -i "s/docker.pkg.github.com\/cs-tao\/whu-library-seat-docker/cstao/g" docker-compose.yml

    - name: Build images for docker hub
      env:
        SEAT_DB_ROOT_PASSWD: ${{ secrets.SEAT_DB_ROOT_PASSWD }}
        SEAT_GHAUTH_CLIENT_SCERET: ${{ secrets.SEAT_GHAUTH_CLIENT_SCERET }}
      if: github.ref == 'refs/heads/master'
      run: docker-compose build
    - name: Deploy images to docker hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        SEAT_DB_ROOT_PASSWD: ${{ secrets.SEAT_DB_ROOT_PASSWD }}
        SEAT_GHAUTH_CLIENT_SCERET: ${{ secrets.SEAT_GHAUTH_CLIENT_SCERET }}
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u cstao -p "$DOCKER_PASSWORD"
        docker-compose push
